### ISSUE TITLE
unifi ap?

### ISSUE THREAD

**Issue by taomi** [fgero/dhcpv6-mod#4]
ap-lr
ap-ac-lr
can use this mod?

**Comment by fgero** [comment]
If I'm not mistaken those acronyms are for Access Points, not Cloud Gateways. The mod is installable only on appliances running UnifiOS with Network app, as stated in the readme, whatever AP you have in front.

**Comment by taomi** [comment]
> If I'm not mistaken those acronyms are for Access Points, not Cloud Gateways. The mod is installable only on appliances running UnifiOS with Network app, as stated in the readme, whatever AP you have in front. 


because unifi ap,
WiFi client ipv6 isn't working, ipv4 OK。
LAN client Ipv4/6 is OK。

3rd gateway,   
AC+AP LAN to LAN
the AP br0 ath0 has ipv6  address,but WiFi client no address

test-ipv6.com    0/10


the fucking  Ubnt community has not solved the problem.

**Comment by fgero** [comment]
Can't test any of that, as I'm using a UDR (also acts as the only WiFi AP in my appartment), and Unifi switches for wired clients. IPv6 seemed to work for smartphones (except sometimes Android who has it's own issues, not related to the UDR AP). In addition, I'm not (at all) knowledgeable about wireless, so I can't help.

**Comment by taomi** [comment]
> Can't test any of that, as I'm using a UDR (also acts as the only WiFi AP in my appartment), and Unifi switches for wired clients. IPv6 seemed to work for smartphones (except sometimes Android who has it's own issues, not related to the UDR AP). In addition, I'm not (at all) knowledgeable about wireless, so I can't help. 

only continue to seek help in the community, otherwise ，only give up unifi ap.

**Comment by fgero** [comment]
As it's not directly related to the dhcpv6-mod repo, and as I can't do much about it, I'm closing this issue. Feel free to reopen if needed.
